# 1.Scrapping

###  1.1 2019-2020

In [4]:
from twitterscraper import query_tweets
import datetime as dt
import pandas as pd
begin_date = dt.date(2019,3,1)
end_date = dt.date(2020,3,1)
#limit = 1000
lang = 'en'

tweets = query_tweets("Nokia" , begindate = begin_date, enddate = end_date , lang = lang)

af = pd.DataFrame(t.__dict__ for t in tweets)
af

INFO: queries: ['Nokia since:2019-03-01 until:2019-03-19', 'Nokia since:2019-03-19 until:2019-04-06', 'Nokia since:2019-04-06 until:2019-04-24', 'Nokia since:2019-04-24 until:2019-05-13', 'Nokia since:2019-05-13 until:2019-05-31', 'Nokia since:2019-05-31 until:2019-06-18', 'Nokia since:2019-06-18 until:2019-07-07', 'Nokia since:2019-07-07 until:2019-07-25', 'Nokia since:2019-07-25 until:2019-08-12', 'Nokia since:2019-08-12 until:2019-08-31', 'Nokia since:2019-08-31 until:2019-09-18', 'Nokia since:2019-09-18 until:2019-10-06', 'Nokia since:2019-10-06 until:2019-10-24', 'Nokia since:2019-10-24 until:2019-11-12', 'Nokia since:2019-11-12 until:2019-11-30', 'Nokia since:2019-11-30 until:2019-12-18', 'Nokia since:2019-12-18 until:2020-01-06', 'Nokia since:2020-01-06 until:2020-01-24', 'Nokia since:2020-01-24 until:2020-02-11', 'Nokia since:2020-02-11 until:2020-03-01']
INFO: Got 695 tweets (695 new).
INFO: Got 1367 tweets (672 new).
INFO: Got 2061 tweets (694 new).
INFO: Got 2770 tweets (709 new).
INFO: Got 3473 tweets (703 new).
INFO: Got 4151 tweets (678 new).
INFO: Got 4870 tweets (719 new).
INFO: Got 5578 tweets (708 new).
INFO: Got 6289 tweets (711 new).
INFO: Got 7017 tweets (728 new).
INFO: Got 7736 tweets (719 new).
INFO: Got 8428 tweets (692 new).
INFO: Got 9127 tweets (699 new).
INFO: Got 9828 tweets (701 new).
INFO: Got 10550 tweets (722 new).
INFO: Got 11272 tweets (722 new).
INFO: Got 12019 tweets (747 new).
INFO: Got 12745 tweets (726 new).
INFO: Got 13474 tweets (729 new).
INFO: Got 14222 tweets (748 new).

,screen_name,username,user_id,tweet_id,tweet_url,timestamp,timestamp_epochs,text,text_html,links,...,has_media,img_urls,video_url,likes,retweets,replies,is_replied,is_reply_to,parent_tweet_id,reply_to_users
0,bsmartins_1,bruna 🕷,1102698936802906113,1127725057537658881,/bsmartins_1/status/1127725057537658881,2019-05-12 23:59:40,1557705580,bruna's top 5 artists this week: Princess Noki...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,1,0,0,False,False,,[]
1,NokiaFansclub1,Nokia Fansclub,1037583997,1127725026365456384,/NokiaFansclub1/status/1127725026365456384,2019-05-12 23:59:33,1557705573,Can Nokia Corporation (NYSE:NOK) Pick Up the P...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[http://dlvr.it/R4Z40x],...,False,[],,0,0,0,False,False,,[]
2,PerezBrolyx100,Luis Perez,1446371816,1127724507253346309,/PerezBrolyx100/status/1127724507253346309,2019-05-12 23:57:29,1557705449,I have a new beautiful neighbors in the backya...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[https://www.instagram.com/p/BxYblqSBy4f/?utm_...,...,False,[],,0,0,0,False,False,,[]
3,JayPronee,Jay Ó Súilleabháin,135177123,1127724488462864384,/JayPronee/status/1127724488462864384,2019-05-12 23:57:24,1557705444,Tut tut @JimCarrey and I was in total agreemen...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,True,[https://pbs.twimg.com/media/D6Z7bwEXsAAVfyi.j...,,0,0,0,False,False,,[]
4,wav_chris,oracle,926345232,1127723811401543682,/wav_chris/status/1127723811401543682,2019-05-12 23:54:43,1557705283,I guarantee he has a Nokia on the belt loop ht...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[https://twitter.com/MadeByTim/status/11276062...,...,False,[],,1,0,1,True,False,,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14217,SunnyRam1,Sunny,168921924,1233676427830185985,/SunnyRam1/status/1233676427830185985,2020-02-29 08:52:35,1582966355,Ohhhh the Nokia 3210 days https://twitter.com...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[https://twitter.com/MikeyCookie_/status/12331...,...,False,[],,0,0,0,False,False,,[]
14218,its_misterio,Misterio,635449207,1233676282488971264,/its_misterio/status/1233676282488971264,2020-02-29 08:52:00,1582966320,They went to the moon on something with less c...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,True,[https://pbs.twimg.com/media/ER7mCljUcAEKT84.jpg],,2,0,1,True,True,1233503519107375107,"[{'screen_name': 'Glenina57', 'user_id': '1137..."
14219,RumiChowd,Rumi Chowdhury,1161766896502366208,1233676125781528577,/RumiChowd/status/1233676125781528577,2020-02-29 08:51:23,1582966283,#RT @rvp: #LI RT ETTelecom https://twitter.com...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[https://twitter.com/ETTelecom/status/12333386...,...,False,[],,0,0,0,False,False,,[]
14220,mildew_on_rice,hairstylist formerly known as boofin blue drink,848016902844764160,1233676078847320065,/mildew_on_rice/status/1233676078847320065,2020-02-29 08:51:12,1582966272,Bring back Nokia brick phones,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,2,0,0,False,False,,[]
14221,OnlyHitNP,OnlyHitNP,1192970154206023680,1233675522456145920,/OnlyHitNP/status/1233675522456145920,2020-02-29 08:48:59,1582966139,#NowPlaying : Green Eggs & Ham by Princess Nok...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[https://onlyhit.us],...,True,[https://pbs.twimg.com/media/ER7lWbvWkAA2Dp0.jpg],,0,0,0,False,False,,[]

### 1.2 2018-2019

In [26]:
from twitterscraper import query_tweets
import datetime as dt
import pandas as pd
begin_date = dt.date(2018,3,1)
end_date = dt.date(2019,3,1)
#limit = 1000
lang = 'en'

tweets = query_tweets("Nokia" , begindate = begin_date, enddate = end_date , lang = lang)

bf = pd.DataFrame(t.__dict__ for t in tweets)
bf

INFO: queries: ['Nokia since:2018-03-01 until:2018-03-19', 'Nokia since:2018-03-19 until:2018-04-06', 'Nokia since:2018-04-06 until:2018-04-24', 'Nokia since:2018-04-24 until:2018-05-13', 'Nokia since:2018-05-13 until:2018-05-31', 'Nokia since:2018-05-31 until:2018-06-18', 'Nokia since:2018-06-18 until:2018-07-06', 'Nokia since:2018-07-06 until:2018-07-25', 'Nokia since:2018-07-25 until:2018-08-12', 'Nokia since:2018-08-12 until:2018-08-30', 'Nokia since:2018-08-30 until:2018-09-17', 'Nokia since:2018-09-17 until:2018-10-06', 'Nokia since:2018-10-06 until:2018-10-24', 'Nokia since:2018-10-24 until:2018-11-11', 'Nokia since:2018-11-11 until:2018-11-29', 'Nokia since:2018-11-29 until:2018-12-18', 'Nokia since:2018-12-18 until:2019-01-05', 'Nokia since:2019-01-05 until:2019-01-23', 'Nokia since:2019-01-23 until:2019-02-10', 'Nokia since:2019-02-10 until:2019-03-01']
INFO: Got 738 tweets (738 new).
INFO: Got 1439 tweets (701 new).
INFO: Got 2155 tweets (716 new).
INFO: Got 2861 tweets (706 new).
INFO: Got 3599 tweets (738 new).
INFO: Got 4335 tweets (736 new).
INFO: Got 5034 tweets (699 new).
INFO: Got 5793 tweets (759 new).
INFO: Got 6503 tweets (710 new).
INFO: Got 7220 tweets (717 new).
INFO: Got 7909 tweets (689 new).
INFO: Got 8605 tweets (696 new).
INFO: Got 9310 tweets (705 new).
INFO: Got 10025 tweets (715 new).
INFO: Got 10748 tweets (723 new).
INFO: Got 11462 tweets (714 new).
INFO: Got 12192 tweets (730 new).
INFO: Got 12913 tweets (721 new).
INFO: Got 13642 tweets (729 new).
INFO: Got 14371 tweets (729 new).

,screen_name,username,user_id,tweet_id,tweet_url,timestamp,timestamp_epochs,text,text_html,links,...,has_media,img_urls,video_url,likes,retweets,replies,is_replied,is_reply_to,parent_tweet_id,reply_to_users
0,PoutySyd,blackityblack,131536017,1067930623669497857,/PoutySyd/status/1067930623669497857,2018-11-28 23:57:56,1543449476,Can y’all stop trying to play Princess Nokia t...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,0,0,0,False,False,,[]
1,thiagoperman,kali uchis modas,201503734,1067930464621613056,/thiagoperman/status/1067930464621613056,2018-11-28 23:57:18,1543449438,princess nokia - goth kid pic.twitter.com/yf32...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,True,[https://pbs.twimg.com/media/DtINGObWwAAh9t_.jpg],,0,0,0,False,False,,[]
2,SMACKHEEM__,Lil Milford,381224557,1067930313442115585,/SMACKHEEM__/status/1067930313442115585,2018-11-28 23:56:42,1543449402,This nigga bas just called my backwoods a prin...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,3,0,0,False,False,,[]
3,dadiyata,Dadiyata🔴,221402621,1067930066368282624,/dadiyata/status/1067930066368282624,2018-11-28 23:55:43,1543449343,Welcome back NOKIA!,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,0,1,0,False,False,,[]
4,prttyonfleek,justinian the great ͪ̏̔̔̒́ͥ̓,827744518057271296,1067929998319747072,/prttyonfleek/status/1067929998319747072,2018-11-28 23:55:27,1543449327,Ok but she is though\nPrincess Nokia is stunni...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,18,1,0,False,True,1067838680608448513,"[{'screen_name': 'americastrash', 'user_id': '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14366,techswami_yt,TECH SWAMI #StayHome 🙏,3503458632,981879329578717184,/techswami_yt/status/981879329578717184,2018-04-05 13:00:49,1522933249,Nokia 6 or Redmi Note 5 Pro|6 Major Points!!: ...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[http://youtu.be/4RF5AWz4ZhI?a],...,False,[],,1,0,0,False,False,,[]
14367,KhalidRafiq133,khalid rafiq,2656540808,981878708867883009,/KhalidRafiq133/status/981878708867883009,2018-04-05 12:58:21,1522933101,Latest Leak: The Nokia 9 will feature Qualcomm...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[https://ift.tt/2uOCbDT],...,False,[],,0,0,0,False,False,,[]
14368,NetMagPakistan,NetMag Pakistan,1528311450,981878627947237376,/NetMagPakistan/status/981878627947237376,2018-04-05 12:58:01,1522933081,Latest Leak: The Nokia 9 will feature Qualcomm...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[https://netmag.pk/latest-leak-nokia-9-feature/],...,False,[],,0,0,0,False,False,,[]
14369,Karthicgowsi007,Karthick,909354772351688704,981878550071410688,/Karthicgowsi007/status/981878550071410688,2018-04-05 12:57:43,1522933063,OMG!I am playing the old Nokia Bounce On my An...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[https://play.google.com/store/apps/details?id...,...,False,[],,0,0,0,False,False,,[]
14370,2_WildFire,Carsten 2WildFire@xda,310761040,981878459654922240,/2_WildFire/status/981878459654922240,2018-04-05 12:57:21,1522933041,Look at xda it is possible to unlock Nokia boo...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,0,0,0,False,True,980369180510756864,"[{'screen_name': 'thiagosposito', 'user_id': '..."

### 1.3 2017-2018

In [1]:
from twitterscraper import query_tweets
import datetime as dt
import pandas as pd
begin_date = dt.date(2017,3,1)
end_date = dt.date(2018,4,30)
#limit = 1000
lang = 'en'

tweets = query_tweets("Nokia" , begindate = begin_date, enddate = end_date , lang = lang)

cf = pd.DataFrame(t.__dict__ for t in tweets)
cf

INFO: {'User-Agent': 'Opera/9.80 (X11; Linux i686; Ubuntu/14.10) Presto/2.12.388 Version/12.16'}
INFO: queries: ['Nokia since:2017-03-01 until:2017-03-22', 'Nokia since:2017-03-22 until:2017-04-12', 'Nokia since:2017-04-12 until:2017-05-03', 'Nokia since:2017-05-03 until:2017-05-25', 'Nokia since:2017-05-25 until:2017-06-15', 'Nokia since:2017-06-15 until:2017-07-06', 'Nokia since:2017-07-06 until:2017-07-27', 'Nokia since:2017-07-27 until:2017-08-18', 'Nokia since:2017-08-18 until:2017-09-08', 'Nokia since:2017-09-08 until:2017-09-29', 'Nokia since:2017-09-29 until:2017-10-20', 'Nokia since:2017-10-20 until:2017-11-11', 'Nokia since:2017-11-11 until:2017-12-02', 'Nokia since:2017-12-02 until:2017-12-23', 'Nokia since:2017-12-23 until:2018-01-13', 'Nokia since:2018-01-13 until:2018-02-04', 'Nokia since:2018-02-04 until:2018-02-25', 'Nokia since:2018-02-25 until:2018-03-18', 'Nokia since:2018-03-18 until:2018-04-08', 'Nokia since:2018-04-08 until:2018-04-30']
INFO: Got 525 tweets (525 new).
INFO: Got 1068 tweets (543 new).
INFO: Got 1591 tweets (523 new).
INFO: Got 2121 tweets (530 new).
INFO: Got 2649 tweets (528 new).
INFO: Got 3185 tweets (536 new).
INFO: Got 3637 tweets (452 new).
INFO: Got 4166 tweets (529 new).
INFO: Got 4672 tweets (506 new).
INFO: Got 5206 tweets (534 new).
INFO: Got 5758 tweets (552 new).
INFO: Got 6299 tweets (541 new).
INFO: Got 6825 tweets (526 new).
INFO: Got 7348 tweets (523 new).
INFO: Got 7886 tweets (538 new).
INFO: Got 8410 tweets (524 new).
INFO: Got 8983 tweets (573 new).
INFO: Got 9533 tweets (550 new).
INFO: Got 10105 tweets (572 new).
INFO: Got 10645 tweets (540 new).

,screen_name,username,user_id,tweet_id,tweet_url,timestamp,timestamp_epochs,text,text_html,links,...,has_media,img_urls,video_url,likes,retweets,replies,is_replied,is_reply_to,parent_tweet_id,reply_to_users
0,TlNYSTVRK,Tiara,826532952,959938659632861185,/TlNYSTVRK/status/959938659632861185,2018-02-03 23:56:25,1517702185,I screamed and threw my brothers Nokia across ...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[https://twitter.com/therealistg1/status/95961...,...,False,[],,0,0,0,False,False,,[]
1,xotwodkyra,Rudy Gobert DPOY,3312154476,959937777231015936,/xotwodkyra/status/959937777231015936,2018-02-03 23:52:55,1517701975,People think they princess Nokia and now they ...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,3,1,0,False,False,,[]
2,geekanoids,Dave Cryer,2136531,959937576189792257,/geekanoids/status/959937576189792257,2018-02-03 23:52:07,1517701927,The #Nokia 3310 is a great phone … so simple y...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[https://www.youtube.com/watch?v=9KRj5UpzFbc],...,True,[https://pbs.twimg.com/media/DVJiI0CVMAAmxFX.jpg],,0,0,0,False,False,,[]
3,JudsonTelemed,Bruce Judson Telemed,437085904,959936831792996352,/JudsonTelemed/status/959936831792996352,2018-02-03 23:49:10,1517701750,FYI: How Nokia’s falling star has led Finland ...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[http://dlvr.it/QDvhKR],...,True,[https://pbs.twimg.com/media/DVJhddIU8AAhyoL.jpg],,0,0,0,False,False,,[]
4,amankhot11,ヽA(^。^)Kノ,838798301218525184,959936791234187264,/amankhot11/status/959936791234187264,2018-02-03 23:49:00,1517701740,are you planning to buy nokia 9?,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,0,0,0,False,True,959484854395060226,"[{'screen_name': 'PalashSinghal15', 'user_id':..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10640,AnkitXharma,Ankit Sharma,543170503,967445142872276992,/AnkitXharma/status/967445142872276992,2018-02-24 17:04:30,1519491870,Finally nokia entered in 2018 with 18:9,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,0,0,0,False,True,967444940002246656,"[{'screen_name': 'gadgetstouse', 'user_id': '9..."
10641,satyamsharma___,Satyam hu bc,3405912213,967445129391828992,/satyamsharma___/status/967445129391828992,2018-02-24 17:04:27,1519491867,Ugly nokia #GTUMWC2018 #GTUBigBangGiveaway,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,1,1,0,False,True,967444940002246656,"[{'screen_name': 'gadgetstouse', 'user_id': '9..."
10642,caiustertius,Riccardo Siviero,445784650,967445116729339905,/caiustertius/status/967445116729339905,2018-02-24 17:04:24,1519491864,I liked a @YouTube video http://youtu.be/rw5IV...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[http://youtu.be/rw5IVu5YMUM?a],...,False,[],,0,0,0,False,False,,[]
10643,Kapitan_Joey,@Kapitan_Joey,382868397,967445058705293312,/Kapitan_Joey/status/967445058705293312,2018-02-24 17:04:10,1519491850,Nokia C6 - Spoilt. Replaced under warranty wit...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,1,1,1,True,False,,[]
10644,HemantS66826430,Hemant Sharma,957306814772649984,967445045577007105,/HemantS66826430/status/967445045577007105,2018-02-24 17:04:07,1519491847,I need Nokia 3 Oreo Update,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,1,0,0,False,True,967356763145166848,"[{'screen_name': 'sarvikas', 'user_id': '46439..."

### 1.4 2016-2017

In [1]:
from twitterscraper import query_tweets
import datetime as dt
import pandas as pd
begin_date = dt.date(2016,2,1)
end_date = dt.date(2017,2,1)
#limit = 1000
lang = 'en'

tweets = query_tweets("Nokia" , begindate = begin_date, enddate = end_date , lang = lang)

df = pd.DataFrame(t.__dict__ for t in tweets)
df

INFO: {'User-Agent': 'Mozilla/5.0 (Windows NT 5.2; RW; rv:7.0a1) Gecko/20091211 SeaMonkey/9.23a1pre'}
INFO: queries: ['Nokia since:2016-02-01 until:2016-02-19', 'Nokia since:2016-02-19 until:2016-03-08', 'Nokia since:2016-03-08 until:2016-03-26', 'Nokia since:2016-03-26 until:2016-04-14', 'Nokia since:2016-04-14 until:2016-05-02', 'Nokia since:2016-05-02 until:2016-05-20', 'Nokia since:2016-05-20 until:2016-06-08', 'Nokia since:2016-06-08 until:2016-06-26', 'Nokia since:2016-06-26 until:2016-07-14', 'Nokia since:2016-07-14 until:2016-08-02', 'Nokia since:2016-08-02 until:2016-08-20', 'Nokia since:2016-08-20 until:2016-09-07', 'Nokia since:2016-09-07 until:2016-09-25', 'Nokia since:2016-09-25 until:2016-10-14', 'Nokia since:2016-10-14 until:2016-11-01', 'Nokia since:2016-11-01 until:2016-11-19', 'Nokia since:2016-11-19 until:2016-12-08', 'Nokia since:2016-12-08 until:2016-12-26', 'Nokia since:2016-12-26 until:2017-01-13', 'Nokia since:2017-01-13 until:2017-02-01']
INFO: Got 562 tweets (562 new).
INFO: Got 1114 tweets (552 new).
INFO: Got 1668 tweets (554 new).
INFO: Got 2185 tweets (517 new).
INFO: Got 2734 tweets (549 new).
INFO: Got 3305 tweets (571 new).
INFO: Got 3858 tweets (553 new).
INFO: Got 4428 tweets (570 new).
INFO: Got 4975 tweets (547 new).
INFO: Got 5544 tweets (569 new).
INFO: Got 6098 tweets (554 new).
INFO: Got 6650 tweets (552 new).
INFO: Got 7196 tweets (546 new).
INFO: Got 7737 tweets (541 new).
INFO: Got 8289 tweets (552 new).
INFO: Got 8848 tweets (559 new).
INFO: Got 9406 tweets (558 new).
INFO: Got 9953 tweets (547 new).
INFO: Got 10540 tweets (587 new).
INFO: Got 11135 tweets (595 new).

,screen_name,username,user_id,tweet_id,tweet_url,timestamp,timestamp_epochs,text,text_html,links,...,has_media,img_urls,video_url,likes,retweets,replies,is_replied,is_reply_to,parent_tweet_id,reply_to_users
0,seductiveyug,moved ☁️,2735261578,806649378953949188,/seductiveyug/status/806649378953949188,2016-12-07 23:59:33,1481155173,i have a Nokia it doesn't support sc,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,0,0,0,False,True,806647962873004032,"[{'screen_name': 'roisdae', 'user_id': '275901..."
1,amielmoyes,Amiel • 아미 엘,212842429,806648914916962304,/amielmoyes/status/806648914916962304,2016-12-07 23:57:42,1481155062,Finland's Impossible Dream Is Happening: Meeti...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[http://www.forbes.com/sites/ewanspence/2016/1...,...,False,[],,1,0,0,False,False,,[]
2,60601Testing,F2 60601 Testing,2786161186,806648192850886656,/60601Testing/status/806648192850886656,2016-12-07 23:54:50,1481154890,Tmobile collaborating with @nokia to test its ...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[http://atjo.es/4n2c],...,False,[],,0,0,0,False,False,,[]
3,socialnet_media,ilikesocialmedia,2810105245,806647894027759616,/socialnet_media/status/806647894027759616,2016-12-07 23:53:39,1481154819,RT: HMD CEO says to expect ‘wide’ Nokia smartp...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[http://bit.ly/2g1QKwb],...,False,[],,0,0,0,False,False,,[]
4,seductiveyug,moved ☁️,2735261578,806647892966592512,/seductiveyug/status/806647892966592512,2016-12-07 23:53:39,1481154819,"my nokia says what's up,,, ilyt","<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,0,0,0,False,True,806647343810482176,"[{'screen_name': 'roisdae', 'user_id': '275901..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11130,Shfzs_xyz_22,DEALS FOR IPHONE,3690184512,779682050727153664,/Shfzs_xyz_22/status/779682050727153664,2016-09-24 14:01:01,1474725661,http://ift.tt/1T7qcD1 #6687 PARROT CK3100 BLU...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[http://ift.tt/1T7qcD1],...,True,[https://pbs.twimg.com/media/CtH8sUeWYAALQwu.jpg],,0,0,0,False,False,,[]
11131,betterhn50,Hacker News 50,774291223842463744,779681851329871872,/betterhn50/status/779681851329871872,2016-09-24 14:00:13,1474725613,52 – Nokia to demonstrate a technique for tera...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[http://www.zdnet.com/article/think-google-fib...,...,False,[],,0,0,0,False,False,,[]
11132,ViTheDeer,"Violet Moon 💜🌙 Stay healthy, stay safe🏳️‍⚧️",737214006,779681342149787649,/ViTheDeer/status/779681342149787649,2016-09-24 13:58:12,1474725492,harder (but not impossible) to do with smartph...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,1,0,0,False,True,779678975056543744,"[{'screen_name': 'airtower_sendai', 'user_id':..."
11133,ks7000,ks7000.net.ve💾😷#FullSnackDeveloper😷,268455349,779681193289588736,/ks7000/status/779681193289588736,2016-09-24 13:57:36,1474725456,The New #Nokia216 and New Nokia 216 Dual Sim (...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[https://www.youtube.com/watch?v=AsKCq1rwG8c],...,False,[],,0,0,0,False,False,,[]
11134,j05e,Jose Marques,14982809,779680998145552385,/j05e/status/779680998145552385,2016-09-24 13:56:50,1474725410,Nokia wanted people to call their Nseries phon...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,0,0,0,False,False,,[]

### 1.5 2015-2016

In [13]:
from twitterscraper import query_tweets
import datetime as dt
import pandas as pd
begin_date = dt.date(2015,1,1)
end_date = dt.date(2016,4,30)
#limit = 1000
lang = 'en'

tweets = query_tweets("Nokia" , begindate = begin_date, enddate = end_date , lang = lang)

ef = pd.DataFrame(t.__dict__ for t in tweets)
ef

INFO: queries: ['Nokia since:2015-01-01 until:2015-01-25', 'Nokia since:2015-01-25 until:2015-02-18', 'Nokia since:2015-02-18 until:2015-03-14', 'Nokia since:2015-03-14 until:2015-04-08', 'Nokia since:2015-04-08 until:2015-05-02', 'Nokia since:2015-05-02 until:2015-05-26', 'Nokia since:2015-05-26 until:2015-06-19', 'Nokia since:2015-06-19 until:2015-07-14', 'Nokia since:2015-07-14 until:2015-08-07', 'Nokia since:2015-08-07 until:2015-08-31', 'Nokia since:2015-08-31 until:2015-09-24', 'Nokia since:2015-09-24 until:2015-10-19', 'Nokia since:2015-10-19 until:2015-11-12', 'Nokia since:2015-11-12 until:2015-12-06', 'Nokia since:2015-12-06 until:2015-12-30', 'Nokia since:2015-12-30 until:2016-01-24', 'Nokia since:2016-01-24 until:2016-02-17', 'Nokia since:2016-02-17 until:2016-03-12', 'Nokia since:2016-03-12 until:2016-04-05', 'Nokia since:2016-04-05 until:2016-04-30']
INFO: Got 713 tweets (713 new).
INFO: Got 1418 tweets (705 new).
INFO: Got 2046 tweets (628 new).
INFO: Got 2790 tweets (744 new).
INFO: Got 3503 tweets (713 new).
INFO: Got 4230 tweets (727 new).
INFO: Got 4960 tweets (730 new).
INFO: Got 5694 tweets (734 new).
INFO: Got 6432 tweets (738 new).
INFO: Got 7160 tweets (728 new).
INFO: Got 7896 tweets (736 new).
INFO: Got 8621 tweets (725 new).
INFO: Got 9317 tweets (696 new).
INFO: Got 10049 tweets (732 new).
INFO: Got 10773 tweets (724 new).
INFO: Got 11480 tweets (707 new).
INFO: Got 12197 tweets (717 new).
INFO: Got 12965 tweets (768 new).
INFO: Got 13697 tweets (732 new).
INFO: Got 14443 tweets (746 new).

,screen_name,username,user_id,tweet_id,tweet_url,timestamp,timestamp_epochs,text,text_html,links,...,has_media,img_urls,video_url,likes,retweets,replies,is_replied,is_reply_to,parent_tweet_id,reply_to_users
0,SierraFane,SierraFane,1238433750,576532804571279361,/SierraFane/status/576532804571279361,2015-03-13 23:58:26,1426291106,Nokia 2690 scallop - quotation evaluated glide...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[http://dlvr.it/8y8qHs],...,False,[],,0,0,0,False,False,,[]
1,GenevieveTheGr8,GenevieveXGarcia,2908919324,576532569493127168,/GenevieveTheGr8/status/576532569493127168,2015-03-13 23:57:30,1426291050,@TMobileHelp - getting weird texts all day. L...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,0,0,2,True,False,,[]
2,cellphonecrap,Cellphone Bargains,80267124,576532170178605057,/cellphonecrap/status/576532170178605057,2015-03-13 23:55:55,1426290955,Nokia Lumia 700112552199 710 Smartphone - GSM ...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[http://c69.co/110635839],...,False,[],,0,0,0,False,False,,[]
3,pornhentaibokep,Porn Hentai Bokep,2993994608,576531751620644864,/pornhentaibokep/status/576531751620644864,2015-03-13 23:54:15,1426290855,Phone Tracker Nokia http://wp.me/p5OIkR-rNo,"<p class=""TweetTextSize js-tweet-text tweet-te...",[http://wp.me/p5OIkR-rNo],...,False,[],,0,0,0,False,False,,[]
4,tekmepikcha,Tek Me PikCha,2659406256,576531398963523584,/tekmepikcha/status/576531398963523584,2015-03-13 23:52:51,1426290771,#StayCalm @RondellPositive is finally on #Inst...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,0,0,0,False,False,,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14438,MarketingWeekEd,Marketing Week,25485248,708247295310106624,/MarketingWeekEd/status/708247295310106624,2016-03-11 11:04:48,1457694288,"eBay, Nokia and Wolf & Badger on what to look ...","<p class=""TweetTextSize js-tweet-text tweet-te...",[http://bit.ly/24Uz4mG],...,True,[https://pbs.twimg.com/media/CdQzKVyXIAAermM.jpg],,4,8,0,False,False,,[]
14439,uop360,"Karol Kwiatek, PhD",23222985,708246809785843713,/uop360/status/708246809785843713,2016-03-11 11:02:52,1457694172,@geonaute @bublcam @Giroptic @Sphericam @nokia...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,False,[],,0,0,0,False,False,,[]
14440,NokiaFansclub1,Nokia Fansclub,1037583997,708246382830686208,/NokiaFansclub1/status/708246382830686208,2016-03-11 11:01:10,1457694070,"Nokia C9 Specifications Leak, Android Under Th...","<p class=""TweetTextSize js-tweet-text tweet-te...",[http://dlvr.it/KlgSjq],...,False,[],,1,1,0,False,False,,[]
14441,GadNoid,Carl John,1117187851,708246359246303232,/GadNoid/status/708246359246303232,2016-03-11 11:01:05,1457694065,"Nokia C9 Specifications Leak, Android Under Th...","<p class=""TweetTextSize js-tweet-text tweet-te...",[http://tinyurl.com/jsze9h4],...,False,[],,0,0,0,False,False,,[]
14442,MobileTechHQ,Mobile Tech HQ,1471521854,708245735150456832,/MobileTechHQ/status/708245735150456832,2016-03-11 10:58:36,1457693916,"Nokia C9 Specifications Leak, Android Under Th...","<p class=""TweetTextSize js-tweet-text tweet-te...",[http://dlvr.it/KlgQn2],...,False,[],,0,0,0,False,False,,[]

In [2]:
af.to_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\2019-2020.csv', index=False)
bf.to_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\2018-2019.csv', index=False)
cf.to_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\2017-2018.csv', index=False)
df.to_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\2016-2017.csv', index=False)
ef.to_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\2015-2016.csv', index=False)

In [8]:
#reading the 5 years of data
import pandas as pd
df0=pd.read_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\2015-2016.csv')
df1=pd.read_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\2016-2017.csv')
df2=pd.read_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\2017-2018.csv')
df3=pd.read_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\2018-2019.csv')
df4=pd.read_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\2019-2020.csv')

In [9]:
#merging the five years of data in to one file
df = pd.concat([df0,df1,df2,df3,df4])
df
df.to_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\Final.csv')

In [71]:
# Loading the file
import pandas as pd
df=pd.read_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\Final.csv',index_col=False)

# 2.Data Cleaning

In [72]:
# splitting the timestamp
df[['Date','Time']] = df['timestamp'].str.split(' ',expand=True)
df[['Day','Month','Year']] = df['Date'].str.split('/',expand=True)

In [73]:
df.head()

,screen_name,username,user_id,tweet_id,tweet_url,timestamp,timestamp_epochs,text,text_html,links,...,replies,is_replied,is_reply_to,parent_tweet_id,reply_to_users,Date,Time,Day,Month,Year
0,SierraFane,SierraFane,1.238434e+09,5.765330e+17,/SierraFane/status/576532804571279361,3/13/2015 23:58,1426291106,Nokia 2690 scallop - quotation evaluated glide...,"<p class=""TweetTextSize js-tweet-text tweet-te...",['http://dlvr.it/8y8qHs'],...,0,False,False,NaN,[],3/13/2015,23:58,3,13,2015
1,GenevieveTheGr8,GenevieveXGarcia,2.908919e+09,5.765330e+17,/GenevieveTheGr8/status/576532569493127168,3/13/2015 23:57,1426291050,@TMobileHelp - getting weird texts all day. L...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,2,True,False,NaN,[],3/13/2015,23:57,3,13,2015
2,cellphonecrap,Cellphone Bargains,8.026712e+07,5.765320e+17,/cellphonecrap/status/576532170178605057,3/13/2015 23:55,1426290955,Nokia Lumia 700112552199 710 Smartphone - GSM ...,"<p class=""TweetTextSize js-tweet-text tweet-te...",['http://c69.co/110635839'],...,0,False,False,NaN,[],3/13/2015,23:55,3,13,2015
3,pornhentaibokep,Porn Hentai Bokep,2.993995e+09,5.765320e+17,/pornhentaibokep/status/576531751620644864,3/13/2015 23:54,1426290855,Phone Tracker Nokia http://wp.me/p5OIkR-rNo,"<p class=""TweetTextSize js-tweet-text tweet-te...",['http://wp.me/p5OIkR-rNo'],...,0,False,False,NaN,[],3/13/2015,23:54,3,13,2015
4,tekmepikcha,Tek Me PikCha,2.659406e+09,5.765310e+17,/tekmepikcha/status/576531398963523584,3/13/2015 23:52,1426290771,#StayCalm @RondellPositive is finally on #Inst...,"<p class=""TweetTextSize js-tweet-text tweet-te...",[],...,0,False,False,NaN,[],3/13/2015,23:52,3,13,2015

### 2.1 Removing Duplicate rows and loading required columns

In [74]:
df.drop_duplicates(subset ="text", 
                     keep = False, inplace = True) 
df.to_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\RemDup.csv')
df=pd.read_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\RemDup.csv',usecols={'text','likes','retweets','replies','Year'})
df.head()

,text,likes,retweets,replies,Year
0,"@ScorpioBert Yes, full circle :) GNT Club Noki...",0,0,1,2015
1,I just upgraded from a zinger to a Nokia lmao ...,0,0,0,2015
2,#deals #savabundle http://ift.tt/1Ac6n1I NEW ...,0,0,0,2015
3,It's so hot today!! @ Nokia Theatre L.A. LIVE...,0,0,0,2015
4,@hVEnigMa nice nokia quality,0,0,1,2015

In [75]:
df['lower']=df['text'].apply(lambda x: " ".join(word.lower() for word in x.split()))
df['lower']=df['lower'].str.replace(r'\W',' ')#removing all the special characters 
df

,text,likes,retweets,replies,Year,lower
0,"@ScorpioBert Yes, full circle :) GNT Club Noki...",0,0,1,2015,scorpiobert yes full circle gnt club noki...
1,I just upgraded from a zinger to a Nokia lmao ...,0,0,0,2015,i just upgraded from a zinger to a nokia lmao ...
2,#deals #savabundle http://ift.tt/1Ac6n1I NEW ...,0,0,0,2015,deals savabundle http ift tt 1ac6n1i new n...
3,It's so hot today!! @ Nokia Theatre L.A. LIVE...,0,0,0,2015,it s so hot today nokia theatre l a live ...
4,@hVEnigMa nice nokia quality,0,0,1,2015,hvenigma nice nokia quality
...,...,...,...,...,...,...
54977,Ohhhh the Nokia 3210 days https://twitter.com...,0,0,0,2020,ohhhh the nokia 3210 days https twitter com ...
54978,They went to the moon on something with less c...,2,0,1,2020,they went to the moon on something with less c...
54979,#RT @rvp: #LI RT ETTelecom https://twitter.com...,0,0,0,2020,rt rvp li rt ettelecom https twitter com...
54980,Bring back Nokia brick phones,2,0,0,2020,bring back nokia brick phones
54981,#NowPlaying : Green Eggs & Ham by Princess Nok...,0,0,0,2020,nowplaying green eggs ham by princess nok...

### 2.2 Removing the stop words

In [76]:
from nltk.corpus import stopwords

In [77]:
stop_words=stopwords.words('english')# built-in dictionary for removing stop words

In [78]:
len(stop_words)

179

In [79]:
# stop words removal
df['stopwords']=df['lower'].apply(lambda x: " ".join(word for word in x.split() if word not in stop_words))
df

,text,likes,retweets,replies,Year,lower,stopwords
0,"@ScorpioBert Yes, full circle :) GNT Club Noki...",0,0,1,2015,scorpiobert yes full circle gnt club noki...,scorpiobert yes full circle gnt club nokia gnt...
1,I just upgraded from a zinger to a Nokia lmao ...,0,0,0,2015,i just upgraded from a zinger to a nokia lmao ...,upgraded zinger nokia lmao struggle
2,#deals #savabundle http://ift.tt/1Ac6n1I NEW ...,0,0,0,2015,deals savabundle http ift tt 1ac6n1i new n...,deals savabundle http ift tt 1ac6n1i new nokia...
3,It's so hot today!! @ Nokia Theatre L.A. LIVE...,0,0,0,2015,it s so hot today nokia theatre l a live ...,hot today nokia theatre l live https instagram...
4,@hVEnigMa nice nokia quality,0,0,1,2015,hvenigma nice nokia quality,hvenigma nice nokia quality
...,...,...,...,...,...,...,...
54977,Ohhhh the Nokia 3210 days https://twitter.com...,0,0,0,2020,ohhhh the nokia 3210 days https twitter com ...,ohhhh nokia 3210 days https twitter com mikeyc...
54978,They went to the moon on something with less c...,2,0,1,2020,they went to the moon on something with less c...,went moon something less computing power nokia...
54979,#RT @rvp: #LI RT ETTelecom https://twitter.com...,0,0,0,2020,rt rvp li rt ettelecom https twitter com...,rt rvp li rt ettelecom https twitter com ettel...
54980,Bring back Nokia brick phones,2,0,0,2020,bring back nokia brick phones,bring back nokia brick phones
54981,#NowPlaying : Green Eggs & Ham by Princess Nok...,0,0,0,2020,nowplaying green eggs ham by princess nok...,nowplaying green eggs ham princess nokia liste...

In [80]:
# Counting all the words in the tweets
Counts=pd.Series(" ".join(df['stopwords']).split()).value_counts()
df10=pd.DataFrame(data=Counts)
df10.head()

             0
nokia    67022
com      23697
http     20432
twitter  13714
https    10899

In [81]:
#Removing the extra words that are not important
other_words=['still','us','go','www','http','https','ly','via','html','u','x','think','tw','nyse','vr','I','e','w','hi','saying','b','oh','the','a','to','and','i','in','it','for','of','on','s','is','they']
df['cleaned_data']=df['lower'].apply(lambda x: " ".join(word for word in x.split() if word not in other_words))
df.head()

,text,likes,retweets,replies,Year,lower,stopwords,cleaned_data
0,"@ScorpioBert Yes, full circle :) GNT Club Noki...",0,0,1,2015,scorpiobert yes full circle gnt club noki...,scorpiobert yes full circle gnt club nokia gnt...,scorpiobert yes full circle gnt club nokia gnt...
1,I just upgraded from a zinger to a Nokia lmao ...,0,0,0,2015,i just upgraded from a zinger to a nokia lmao ...,upgraded zinger nokia lmao struggle,just upgraded from zinger nokia lmao struggle
2,#deals #savabundle http://ift.tt/1Ac6n1I NEW ...,0,0,0,2015,deals savabundle http ift tt 1ac6n1i new n...,deals savabundle http ift tt 1ac6n1i new nokia...,deals savabundle ift tt 1ac6n1i new nokia lumi...
3,It's so hot today!! @ Nokia Theatre L.A. LIVE...,0,0,0,2015,it s so hot today nokia theatre l a live ...,hot today nokia theatre l live https instagram...,so hot today nokia theatre l live instagram co...
4,@hVEnigMa nice nokia quality,0,0,1,2015,hvenigma nice nokia quality,hvenigma nice nokia quality,hvenigma nice nokia quality

### 2.3 Lemmatization

In [82]:
from textblob import Word

In [83]:
df['lemmatized']=df['cleaned_data'].apply(lambda x: " ".join(Word(word).lemmatize() for word in x.split()))
df.head()

,text,likes,retweets,replies,Year,lower,stopwords,cleaned_data,lemmatized
0,"@ScorpioBert Yes, full circle :) GNT Club Noki...",0,0,1,2015,scorpiobert yes full circle gnt club noki...,scorpiobert yes full circle gnt club nokia gnt...,scorpiobert yes full circle gnt club nokia gnt...,scorpiobert yes full circle gnt club nokia gnt...
1,I just upgraded from a zinger to a Nokia lmao ...,0,0,0,2015,i just upgraded from a zinger to a nokia lmao ...,upgraded zinger nokia lmao struggle,just upgraded from zinger nokia lmao struggle,just upgraded from zinger nokia lmao struggle
2,#deals #savabundle http://ift.tt/1Ac6n1I NEW ...,0,0,0,2015,deals savabundle http ift tt 1ac6n1i new n...,deals savabundle http ift tt 1ac6n1i new nokia...,deals savabundle ift tt 1ac6n1i new nokia lumi...,deal savabundle ift tt 1ac6n1i new nokia lumia...
3,It's so hot today!! @ Nokia Theatre L.A. LIVE...,0,0,0,2015,it s so hot today nokia theatre l a live ...,hot today nokia theatre l live https instagram...,so hot today nokia theatre l live instagram co...,so hot today nokia theatre l live instagram co...
4,@hVEnigMa nice nokia quality,0,0,1,2015,hvenigma nice nokia quality,hvenigma nice nokia quality,hvenigma nice nokia quality,hvenigma nice nokia quality

# 3.Sentiment analysis

In [84]:
from textblob import TextBlob

In [85]:
df['polarity']=df['lemmatized'].apply(lambda x: TextBlob(x).sentiment[0])# for finding polarity
df['subjectivity']=df['lemmatized'].apply(lambda x: TextBlob(x).sentiment[1])# for finding subjectivity
df.drop(['lower','stopwords','cleaned_data'],axis=1,inplace=True)# dropping the unnecessary columns
df.to_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\polaritytweets.csv')
df.head()

,text,likes,retweets,replies,Year,lemmatized,polarity,subjectivity
0,"@ScorpioBert Yes, full circle :) GNT Club Noki...",0,0,1,2015,scorpiobert yes full circle gnt club nokia gnt...,0.383333,0.650000
1,I just upgraded from a zinger to a Nokia lmao ...,0,0,0,2015,just upgraded from zinger nokia lmao struggle,0.600000,1.000000
2,#deals #savabundle http://ift.tt/1Ac6n1I NEW ...,0,0,0,2015,deal savabundle ift tt 1ac6n1i new nokia lumia...,-0.015152,0.443939
3,It's so hot today!! @ Nokia Theatre L.A. LIVE...,0,0,0,2015,so hot today nokia theatre l live instagram co...,0.193182,0.675000
4,@hVEnigMa nice nokia quality,0,0,1,2015,hvenigma nice nokia quality,0.600000,1.000000

In [86]:
# Counting likes, tweets and retweets
df['polarity_text']=0
pos_likes=neg_likes=neu_likes=pos_retweets=neg_retweets=neu_retweets=pos_tweets=neg_tweets=neu_tweets=0
y=-1
for x in df[('polarity')]:
    if x>0:
        y=y+1
        df['polarity_text'][y]='positive'
        pos_likes=pos_likes+df['likes'][y]
        pos_retweets=pos_retweets+df['retweets'][y]
        pos_tweets=pos_tweets+1
               
    elif x==0:
        y=y+1
        df['polarity_text'][y]='neutral'
        neu_likes=neu_likes+df['likes'][y]
        neu_retweets=neu_retweets+df['retweets'][y]
        neu_tweets=neu_tweets+1
        
    else:
        y=y+1
        df['polarity_text'][y]='negative'
        neg_likes=neg_likes+df['likes'][y]
        neg_retweets=neg_retweets+df['retweets'][y]
        neg_tweets=neg_tweets+1
        
print('positive tweets =',pos_tweets,' negative tweets =',neg_tweets,' neutral tweets =',neu_tweets)       
print('positive likes =', pos_likes,' negative likes =', neg_likes,' neutral likes =', neu_likes,'positive retweet =', pos_retweets,' negative retweet =', neg_retweets,' neutral retweet =', neu_retweets)

C:\Users\narayana\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\narayana\Anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\narayana\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\narayana\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

positive tweets = 22392  negative tweets = 7337  neutral tweets = 25253
positive likes = 65320  negative likes = 16950  neutral likes = 49329 positive retweet = 13917  negative retweet = 3341  neutral retweet = 13216

In [87]:
df.head()

,text,likes,retweets,replies,Year,lemmatized,polarity,subjectivity,polarity_text
0,"@ScorpioBert Yes, full circle :) GNT Club Noki...",0,0,1,2015,scorpiobert yes full circle gnt club nokia gnt...,0.383333,0.650000,positive
1,I just upgraded from a zinger to a Nokia lmao ...,0,0,0,2015,just upgraded from zinger nokia lmao struggle,0.600000,1.000000,positive
2,#deals #savabundle http://ift.tt/1Ac6n1I NEW ...,0,0,0,2015,deal savabundle ift tt 1ac6n1i new nokia lumia...,-0.015152,0.443939,negative
3,It's so hot today!! @ Nokia Theatre L.A. LIVE...,0,0,0,2015,so hot today nokia theatre l live instagram co...,0.193182,0.675000,positive
4,@hVEnigMa nice nokia quality,0,0,1,2015,hvenigma nice nokia quality,0.600000,1.000000,positive

In [42]:
# dividing negative tweets
nf=df.loc[(df['polarity_text']=='negative') & (df['likes']>=20)]
nf.to_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\negative_tweets.csv')

In [19]:
# dividing neutral tweets
nef=df.loc[(df['polarity_text']=='neutral') & (df['likes']>=20)]
nef.to_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\neutral_tweets.csv')

In [20]:
df['likes'].sum() #total likes

131599

In [21]:
df['retweets'].sum() #total retweets

30474

In [88]:
df.to_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\polaritytweetstext.csv')

# 4.Final data

In [113]:
#Storing the values into a csv file
tweets=[pos_tweets,neu_tweets,neg_tweets]
retweets=[pos_retweets,neu_retweets,neg_retweets]
likes=[pos_likes,neu_likes,neg_likes]
polarity=['Positive','Neutral','Negative']
pf=pd.read_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\Final.csv',usecols={})
pf['Polarity']=polarity
pf['Tweets']=tweets
pf['Likes']=likes
pf['Retweets']=retweets
pf

   Polarity  Tweets  Likes  Retweets
0  Positive   22392  65320     13917
1   Neutral   25253  49329     13216
2  Negative    7337  16950      3341

In [114]:
pf.to_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\sentiment.csv')

# 5.Area wise analysis

In [2]:
import pandas as pd
df=pd.read_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\polaritytweetstext.csv') 
negative_tweet=df[(df['polarity_text']=='negative')] 
negative_tweet.to_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\all negative.csv')
df=pd.read_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\all negative.csv')
Counts=pd.Series(" ".join(df['lemmatized']).split()).value_counts()
df=pd.DataFrame(data=Counts)
df.to_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\negative_counts.csv')
df.head()

            0
nokia    8883
com      2660
phone    1735
twitter  1578
with     1158

In [3]:
df=pd.read_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\all negative.csv',usecols={'text'})
#Counting the specific values from tweets
hardware=df[(df.text.str.contains('camera',case=False))|(df.text.str.contains('charger',case=False))|(df.text.str.contains('pin',case=False))|(df.text.str.contains('cable',case=False))|(df.text.str.contains('screen',case=False))|(df.text.str.contains('battery',case=False))|(df.text.str.contains('pixel',case=False))]
service=df[df.text.str.contains('service',case=False)|(df.text.str.contains('repair',case=False))|(df.text.str.contains('quality',case=False))|(df.text.str.contains('slow',case=False))|(df.text.str.contains('security',case=False))|(df.text.str.contains('performance',case=False))] 
update=df[(df.text.str.contains('update',case=False))|(df.text.str.contains('android',case=False))|(df.text.str.contains('symbian',case=False))|(df.text.str.contains('updated',case=False))|(df.text.str.contains('outdated',case=False))|(df.text.str.contains('upgrade',case=False))|(df.text.str.contains('repace',case=False))]
ram=df[(df.text.str.contains('3gb',case=False))|(df.text.str.contains('2gb',case=False))]
price=df[(df.text.str.contains('price',case=False))|(df.text.str.contains('expensive',case=False))|(df.text.str.contains('prize',case=False))]
storage=df[(df.text.str.contains('storage',case=False))|(df.text.str.contains('8gb',case=False))|(df.text.str.contains('32gb',case=False))|(df.text.str.contains('64gb',case=False))|(df.text.str.contains('3gb',case=False))|(df.text.str.contains('space',case=False))|(df.text.str.contains('size',case=False))|(df.text.str.contains('memory',case=False))] 
network=df[(df.text.str.contains('gsm',case=False))|(df.text.str.contains('2g',case=False))|(df.text.str.contains('3g',case=False))|(df.text.str.contains('4g',case=False))]
Hardware=hardware.text.count()
Service=service.text.count()
Update=update.text.count()
Ram=ram.text.count()
Price=price.text.count()
Storage=storage.text.count()
Network=network.text.count()

In [4]:
#Storing the values
area=['Hardware','Service','Update','Ram','Price','Storage','Network']
values=[Hardware,Service,Update,Ram,Price,Storage,Network]
pf=pd.read_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\Final1.csv',usecols={})
pf['Area']=area
pf['Values']=values
pf.to_csv('C:\\Users\\narayana\\Desktop\\msc datascience\\social media analytics\\assesment\\Area_wise.csv')
pf

       Area  Values
0  Hardware     751
1   Service     413
2    Update     567
3       Ram      65
4     Price     179
5   Storage     250
6   Network     354